travel-iff_old-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "welcome#index"
  resources :bus_companies
  resources :vehicles
  resources :travels
  resources :events
  resources :students
  resources :drivers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

travel-iff_old-master/app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id                        :integer          not null, primary key
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  person_id                 :integer
#  registration_file_name    :string
#  registration_content_type :string
#  registration_file_size    :integer
#  registration_updated_at   :datetime
#

class Student < ApplicationRecord
	belongs_to :person, inverse_of: :students
	belongs_to :event
	has_many :student_events
	has_many :events, through: :student_events

	has_attached_file :registration, content_type: ["image/jpeg", "image/png"], styles: {
      thumb: "100x100#",
      small: "150x150>",
      medium: "200x200" }
  	validates_attachment :registration, presence: true,
  		content_type: { content_type: ["image/jpeg", "image/png"] }
	
	#validates :registration, uniqueness: true
	validates :registration, presence: true, on: :new
	validates :person, presence: true

	accepts_nested_attributes_for :person
	accepts_nested_attributes_for :student_events

	paginates_per 5
end

travel-iff_old-master/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :set_events, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @q = Student.ransack(params[:q])
    @students = @q.result(distinct: true).page params[:page]
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @student.build_person
  end

  # GET /students/1/edit
  def edit
    @student.student_events.build
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: t('Student was successfully created.') }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: t('Student was successfully updated.') }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: t('Student was successfully destroyed.') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
      @person = @student.person
    end

    def set_events
      @events = Event.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:registration, 
        person_attributes: [:name, :phone, :identity, :cpf, :birth, :id],
        student_events_attributes: [:event_id, :id])
    end
end

travel-iff_old-master/app/helpers/students_helper.rb
module StudentsHelper
end

travel-iff_old-master/app/views/students/_form.html.erb
<%= simple_form_for @student, wrapper: :horizontal_form do |f| %>
  <%= f.error_notification %>
<div class="form-horizontal col-sm-offset-1 col-sm-7">
  <div class="panel panel-info">
  <div class="panel-heading "><%=t("Table_student")%></div>
    <div class="panel-body">
      <div class="form-inputs">
          <%= f.simple_fields_for :person, wrapper: :horizontal_form do |person| %>
            <%= person.input :name %>
            <%= person.input :phone %>
            <%= person.input :identity %>
            <%= person.input :cpf %>
            <%= person.input :birth, as: :bootstrap_datepicker, input_html: {class: "form-control"} %>
          <% end %>
          <%= f.input :registration, as: :file, wrapper: :horizontal_form %>
      </div>

      <div class="form-actions">
          <%= f.button :submit, class: "btn btn-info" %>
      </div>
    </div>  
  </div>
</div>     
<% end %>

travel-iff_old-master/app/views/students/edit.html.erb
<div class='page-header'>
  <h1><%= t('Editing Student') %>
    <div class='pull-right'>
      <%= link_to students_path, class: 'btn btn-warning' do %>
        <i class='glyphicon glyphicon-backward'></i> <%= t('Back') %>
      <% end %>
    </div>
  </h1>
</div>

<%= simple_form_for @student, wrapper: :horizontal_form do |f| %>
  <%= f.error_notification %>
<div class="form-horizontal col-sm-offset-1 col-sm-7">
  <div class="panel panel-info">
  <div class="panel-heading "><%=t("Table_student")%></div>
    <div class="panel-body">
      <div class="form-inputs">
          <%= f.simple_fields_for :person, wrapper: :horizontal_form do |person| %>
            <%= person.input :name %>
            <%= person.input :phone %>
            <%= person.input :identity %>
            <%= person.input :cpf %>
            <%= person.input :birth, as: :bootstrap_datepicker, input_html: {class: "form-control"} %>
            <%= person.hidden_field :id, value: @person.id %>
          <% end %>
          <%= f.input :registration, as: :file, wrapper: :horizontal_form %>

		      <%= f.simple_fields_for :student_events, wrapper: :horizontal_form do |student_event| %>
            <%= student_event.input :event_id, collection: @events %>
            <!--%= student_event.hidden_field :student_events_ids, value: @event.id %-->
          <% end %>
      </div>

      <div class="form-actions">
          <%= f.button :submit, class: "btn btn-info" %>
      </div>
    </div>  
  </div>
</div>     
<% end %>

travel-iff_old-master/app/views/students/index.html.erb
<div class="table table-responsive table-hover table-stripped' id='travels">
  <div class="well">
    <h4><%=t '.Search travels'%></h4>
      <div class="input-group">
        <%= search_form_for @q, wrapper: :horizontal_form do |f| %>
          <%= f.label :person_name_cont %>
          <%= f.search_field :person_name_cont, placeholder: 'Pesquisar por Aluno', class: "form-control" %>
          <%= f.label :person_cpf_cont %>
          <%= f.search_field :person_cpf_cont, placeholder: 'Pesquisar por Cpf', class: "form-control" %>
          <%= f.button :submit, name: "Pesquisar", class: 'btn btn-sm btn-warning', id: 'search' do %>
            <i class="glyphicon glyphicon-search"></i>
          <% end %>
        <% end %> 
      </div>       
  </div>

<div class='page-header'>
  <h1>
    <%= t('Listing Students') %> (<%= @students.count %>)  <small><%= @student %></small>
    <div class='pull-right'>
      <%= link_to new_student_path(), class: 'btn btn-info' do %>
        <i class='glyphicon glyphicon-plus'></i> <%= t('New Student') %>
      <% end %>
    </div>
  </h1>
</div>

<table class='table table-responsive table-hover table-stripped' id='students'>
  <thead>
  <tr>
      <th><%=t("Name")%></th>
      <th><%=t("Cpf")%></th>
    <th></th>
  </tr>

  </thead>

  <tbody>
    <% @students.each do |student| %>
    <tr>
        <td><%= student.person.name %></td>
        <td><%= student.person.cpf %></td>
      <td class='actions text-center'>
        <%= link_to t('Show'), student_path(student), class: 'btn btn-sm btn-info' %>
        <%= link_to t('Edit'), edit_student_path(student), class: 'btn btn-sm btn-warning' %>
        <%= link_to t('Destroy'), student_path(student), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: t('Are you sure?') } %>
        <%= link_to t("Image"), student.registration.url(:original, false),class: 'btn btn-sm btn-teste', id: 'image' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @students %>

travel-iff_old-master/app/views/students/new.html.erb
<div class='page-header'>
  <h1><%= t('New Student') %>
    <div class='pull-right'>
      <%= link_to students_path, class: 'btn btn-warning' do %>
        <i class='glyphicon glyphicon-backward'></i> <%= t('Back') %>
      <% end %>
    </div>
  </h1>
</div>

<%= render 'form' %>

travel-iff_old-master/app/views/students/show.html.erb
<div class='page-header'>
  <h1>
    <%= t('Student Info') %>
    <div class='pull-right'>
      <%= link_to edit_student_path(@student), class: 'btn btn-info' do %>
        <i class='glyphicon glyphicon-pencil'></i> <%= t('Edit') %>
      <% end %>
      <%= link_to students_path, class: 'btn btn-warning' do %>
        <i class='glyphicon glyphicon-backward'></i> <%= t('Back') %>
      <% end %>
    </div>
  </h1>
</div>

<div class='panel panel-default'>
  <div class='panel-body'>
    <p>
      <strong><%=t("Name")%></strong>
      <%= @student.person.name %>
    </p>
    <p>
      <strong><%=t("Phone")%></strong>
      <%= @student.person.phone %>
    </p>
    <p>
      <strong><%=t("Identity")%></strong>
      <%= @student.person.identity %>
    </p>
    <p>
      <strong><%=t("Cpf")%></strong>
      <%= @student.person.cpf %>
    </p>
    <p>
      <strong><%=t("Birth")%></strong>
      <%= @student.person.birth %>
    </p>
    <p>
      <strong><%=t("Registration")%></strong>
        <%= link_to image_tag(@student.registration.url(:small)),
         @student.registration.url(:original) %>
        <p>
    </p>
  </div>
</div>