travel-iff_old-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "welcome#index"
  resources :bus_companies
  resources :vehicles
  resources :travels
  resources :events
  resources :students
  resources :drivers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

travel-iff_old-master/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

travel-iff_old-master/app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to t('Edit account'), edit_user_registration_path %></li>
  <li><%= link_to t('Sign out'), destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to t('Sign in'), new_user_session_path %></li>
  <li><%= link_to t('Sign up'), new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to t('Users'), users_path %></li>
  <% end %>
<% end %>

travel-iff_old-master/app/views/layouts/_navigation.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#page-top"><%=t("Travel IFF")%></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <%= render 'layouts/nav_links_for_auth.html.erb' %>
                    <!--li class="page-scroll">
                        <a href="#portfolio"><%=t("Portfolio")%></a>
                    </li-->
                    <!--li class="page-scroll">
                        <a href="#about"><%=t("About")%></a>
                    </li-->
                    <!--li class="page-scroll">
                        <a href="#contact">Contact</a>
                    </li-->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

travel-iff_old-master/app/views/layouts/_side_bar.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="nav-side-menu">
    <div class="brand">IFF</div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
  
        <div class="menu-list">
  
            <ul id="menu-content" class="menu-content collapse out">
                <li>
                  <a>
                    <i><%= link_to t("Travels"), travels_path, class: 'fa fa-plane fa-lg' %></i>
                  </a>
                </li>

                 <li>
                  <a>
                    <i><%= link_to t("Events"), events_path, class: 'fa fa-suitcase fa-lg' %></i>
                  </a>
                  </li>

                 <li>
                  <a>
                    <i><%= link_to t("Students"), students_path, class: 'fa fa-users fa-lg' %></i>
                  </a>
                </li>

                <li>
                  <a>
                  <i><%= link_to t("Drivers"), drivers_path, class: 'fa fa-dashboard fa-lg' %></i>
                  </a>
                </li>

                <li>
                  <a>
                    <i><%= link_to t("Vehicle"), vehicles_path, class: 'fa fa-bus fa-lg' %></i>
                  </a>
                </li>

                <li>
                  <a>
                    <i><%= link_to t("Bus Company"), bus_companies_path, class: 'fa fa-building-o fa-lg' %></i>
                  </a>
                </li>
            </ul>
     </div>
</div>

travel-iff_old-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=t("TravelIff")%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= render 'layouts/navigation.html.erb' %>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/side_bar' %>
    <%= yield %>
  </body>
</html>