travel-iff_old-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "welcome#index"
  resources :bus_companies
  resources :vehicles
  resources :travels
  resources :events
  resources :students
  resources :drivers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

travel-iff_old-master/app/models/vehicle.rb
# == Schema Information
#
# Table name: vehicles
#
#  id             :integer          not null, primary key
#  seat           :integer
#  price          :float
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  travel_id      :integer
#  bus_company_id :integer
#  order_number   :integer
#

class Vehicle < ApplicationRecord
	belongs_to :travel
	belongs_to :bus_company
	has_many :drivers

	validates :seat, presence: true
	validates :seat, numericality: true
	validates :order_number, presence: true
	validates :order_number, numericality: true
	validates :price, presence: true
	validates :price, numericality: true
	validates :travel_id, presence: true
	validates :bus_company_id, presence: true

	def to_s
	   "#{bus_company.name} -- Veículo(#{order_number})"	
	end

	paginates_per 5
end

travel-iff_old-master/app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all.order('created_at DESC').page params[:page]
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: t('Vehicle was successfully created.') }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: t('Vehicle was successfully updated.') }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: t('Vehicle was successfully destroyed.') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:seat, :order_number, :price, :travel_id, :bus_company_id)
    end
end

travel-iff_old-master/app/helpers/vehicles_helper.rb
module VehiclesHelper
end

travel-iff_old-master/app/views/vehicles/_form.html.erb
<%= simple_form_for @vehicle, wrapper: :horizontal_form do |f| %>
  <%= f.error_notification %>
<div class="form-horizontal col-sm-offset-1 col-sm-7">
  <div class="panel panel-info">
  <div class="panel-heading "><%=t("Table_vehicle")%></div>
    <div class="panel-body">
      <div class="form-inputs">
          <%= f.input :seat %>
          <%= f.input :order_number %>
          <%= f.input :price %>
          <%= f.association :travel %>
          <%= f.association :bus_company %>
      </div>

      <div class="form-actions">
          <%= f.button :submit, class: "btn btn-info" %>
      </div>
    </div>  
  </div>
</div>     
<% end %>

travel-iff_old-master/app/views/vehicles/edit.html.erb
<div class='page-header'>
  <h1><%= t('Editing Vehicle') %>
    <div class='pull-right'>
      <%= link_to vehicles_path, class: 'btn btn-warning' do %>
        <i class='glyphicon glyphicon-backward'></i> <%= t('Back') %>
      <% end %>
    </div>
  </h1>
</div>

<%= render 'form' %>

travel-iff_old-master/app/views/vehicles/index.html.erb
<div class='page-header'>
  <h1>
    <%= t('Listing Vehicles') %> (<%= @vehicles.count %>)  <small><%= @vehicle %></small>
    <div class='pull-right'>
      <%= link_to new_vehicle_path(), class: 'btn btn-info' do %>
        <i class='glyphicon glyphicon-plus'></i> <%= t('New Vehicle') %>
      <% end %>
    </div>
  </h1>
</div>

<table class='table table-responsive table-hover table-stripped' id='vehicles'>
  <thead>
  <tr>
      <th><%=t("Seat")%></th>
      <th><%=t("Number")%></th>
      <th><%=t("Price")%></th>
    <th></th>
  </tr>

  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
    <tr>
        <td><%= vehicle.seat %></td>
        <td><%= vehicle.order_number %></td>
        <td><%= vehicle.price %></td>
      <td class='actions text-center'>
        <%= link_to t('Show'), vehicle_path(vehicle), class: 'btn btn-sm btn-info' %>
        <%= link_to t('Edit'), edit_vehicle_path(vehicle), class: 'btn btn-sm btn-warning' %>
        <%= link_to t('Destroy'), vehicle_path(vehicle), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: t('Are you sure?') } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @vehicles %>

travel-iff_old-master/app/views/vehicles/new.html.erb
<div class='page-header'>
  <h1><%= t('New Vehicle') %>
    <div class='pull-right'>
      <%= link_to vehicles_path, class: 'btn btn-warning' do %>
        <i class='glyphicon glyphicon-backward'></i> <%= t('Back') %>
      <% end %>
    </div>
  </h1>
</div>

<%= render 'form' %>

travel-iff_old-master/app/views/vehicles/show.html.erb
<div class='page-header'>
  <h1>
    <%= t('Vehicle Info') %>
    <div class='pull-right'>
      <%= link_to edit_vehicle_path(@vehicle), class: 'btn btn-info' do %>
        <i class='glyphicon glyphicon-pencil'></i> <%= t('Edit') %>
      <% end %>
      <%= link_to vehicles_path, class: 'btn btn-warning' do %>
        <i class='glyphicon glyphicon-backward'></i> <%= t('Back') %>
      <% end %>
    </div>
  </h1>
</div>

<div class='panel panel-default'>
  <div class='panel-body'>
    <p>
      <strong><%=t("Seat")%></strong>
      <%= @vehicle.seat %>
    </p>
    <p>
      <strong><%=t("Number")%></strong>
      <%= @vehicle.order_number %>
    </p>
    <p>
      <strong><%=t("Price")%></strong>
      <%= @vehicle.price %>
    </p>
  </div>
</div>